### ISSUE TITLE
replace spaces by another character

### ISSUE THREAD

**Issue by 4zv4l** [treeform/urlly#5]
I have this Nim code in here
```nim
import puppy
import os

let
  url = "https://funquizzes.fun/uploads/manga/One%20Punch%20Man/"

echo url
echo execShellCmd("curl "&url)
echo fetch(url)
```
with curl it works but with puppy it doesn't work because it seems that the fetch function replace spaces or %20 by '+' anyway which the server I try to fetch doesn't accept.
would be better not replacing it or use encodeUrl.
https://github.com/treeform/urlly/blob/master/src/urlly.nim#L48-L49

**Comment by treeform** [comment]
Thank you for the issue!

This should be fixed in 1.0.1. 

Feel free to reopen if you still have issues.
